# Homework 2 Part 1

Name: Kristina
<br>
Surname: Ghahramanyan

In [7]:
import numpy as np

**Problem 1**

Create a numpy array of dimensions (5,5) with random numbers in range \[0, 1) and print its shape, number of dimensions and data type of its elements.

In [8]:
import random
b = []
def func(lst):
    while len(lst) < 5:
        lst.append(random.random())
    return lst

while len(b) < 5:
    b.append(func([]))

arr = np.array(b)
print(arr)

#The same code as above, but with a function np.random.random()
#arr = np.random.random((5,5))
#print(arr)

print(f"\n Shape of the array is {arr.shape} \n Number of dimensions of the array is {arr.ndim} \n Data type of array's elements is {arr.dtype}")

[[0.62937893 0.09997884 0.59172568 0.88016394 0.58224659]
 [0.50821368 0.68772583 0.65402422 0.01020005 0.92209997]
 [0.46482593 0.39679028 0.33326197 0.37252638 0.38987137]
 [0.12440553 0.77441223 0.67468397 0.87715298 0.10181675]
 [0.28869301 0.96448492 0.78475268 0.47036851 0.32259436]]

 Shape of the array is (5, 5) 
 Number of dimensions of the array is 2 
 Data type of array's elements is float64


**Problem 2**

Change the data type of elements of the numpy array created in Problem 1 to int and keep only even numbers in the array (the shape of output does not matter).

In [9]:
#if I understood correctly, the numbers which were more than 0.5 should have been converted to 1s instead of 0s.
#I tried to create the original array with different ways, but after changing the data type, I never could achieve 1s. 
#Nonetheless, the code works, if we change the range to [0,1], it actually outputs only 0s.
arr2 = arr.astype(int)
print(arr2)
print(arr2.dtype)
print(arr2[arr2%2==0])

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
int32
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


**Problem 3**

Create a numpy array of zeros, a numpy arrays of ones, and an identity matrix of shape (7,7) (all 3). Sum the arrays and print the result.

In [24]:
arrof0 = np.zeros((7,7),dtype=int)
arrof1 = np.ones((7,7),dtype=int)
mat = np.eye((7), dtype=int)
print(f" Array of zeros \n{arrof0} \n\n Array of ones \n {arrof1} \n\n Identity matrix \n {mat} \n\n")
final = arrof0 + arrof1 + mat
print(f"Sum of the arrays \n {final}")

 Array of zeros 
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]] 

 Array of ones 
 [[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]] 

 Identity matrix 
 [[1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1]] 


Sum of the arrays 
 [[2 1 1 1 1 1 1]
 [1 2 1 1 1 1 1]
 [1 1 2 1 1 1 1]
 [1 1 1 2 1 1 1]
 [1 1 1 1 2 1 1]
 [1 1 1 1 1 2 1]
 [1 1 1 1 1 1 2]]


**Problem 4**

Create 10x10 multiplication table as a numpy array.

In [25]:
# Here is the output
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]

SyntaxError: invalid syntax (<ipython-input-25-a569d510e5bd>, line 2)

In [26]:
arrtable = np.ones((10,10),dtype=int)

for i in range(10):
    for j in range(10):
        arrtable[i][j] = (i+1) * (j+1)
        
        
print(arrtable)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


**Problem 5**

Use np.r_ function to generate an array of all single digit precision floating numbers between [0,1] .
The numbers are 0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, and 1. .

In [27]:
a = np.r_[0:1.1:0.1]
print(a)

# same thing with arange
#b = np.arange(0, 1.1, 0.1, dtype=float)
#print(b)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


**Problem 6**

Use np.c_ function to generate a numpy array where the first column contains even integers between [1,10] and the second columns contain the odd numbers in the same range.

In [28]:
c = np.c_[2:11:2, 1:11:2]
print(c)

[[ 2  1]
 [ 4  3]
 [ 6  5]
 [ 8  7]
 [10  9]]


**Problem 7**

Generate a 10000x10000 dimensional matrix with numpy zeroes, resizing numpy array with one element equal to 0, tiling list [0], array+list operations with list [0], and array+list_comprehension approaches, and calculate the execution time.

In [30]:
%timeit np.zeros((10000,10000),dtype=int)

%timeit np.array([0]).resize(10000,10000)

%timeit np.tile(np.array([0]), (10000, 10000))

%timeit np.array([0] * 10000)

%timeit np.array([0 * i for i in range(10000)])

17.2 µs ± 57.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
72.5 ms ± 4.47 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
293 ms ± 6.81 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
474 µs ± 12.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
926 µs ± 46.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)




**Problem 8**

Generate an one-dimensional array of integers between [0,31337] and compute the mean, variance, max, and min of that array. Perform the same operations using built-in Python operations and list comprehension. Calculate the execution time in both cases.

In [31]:
arrone = np.arange(0,31337)

print(f" Mean: {arrone.mean()}")
%timeit arrone.mean()

print(f"\n Variance: {arrone.var()}")
%timeit arrone.var()

print(f"\n Max: {arrone.max()}")
%timeit arrone.max()

print(f"\n Min: {arrone.min()}")
%timeit arrone.min()


print("\n")


print(f"\n Mean: {sum(arrone) / len(arrone)}")
%timeit sum(arrone) / len(arrone)

print(f"\n Variance: {[sum((i - (sum(arrone)/len(arrone))) ** 2 for i in arrone) / len(arrone)]}")
%timeit [sum((i - (sum(arrone)/len(arrone))) ** 2 for i in arrone) / len(arrone)] #works, but takes a really long time
#same code as above (Variance), but runs much faster
#mean = sum(arrone) / len(arrone)
#l = len(arrone)
#%timeit [sum((i - mean) ** 2 for i in arrone) / l]

print(f"\n Max: {max([i for i in arrone if i > arrone[0]])}")
%timeit max([i for i in arrone if i > arrone[0]])

print(f"\n Min: {min([i if arrone[0] == i else arrone[0] for i in arrone])}")
%timeit min([i if arrone[0] == i else arrone[0] for i in arrone])

 Mean: 15668.0
29.2 µs ± 296 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

 Variance: 81833964.0
80.1 µs ± 1.41 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)

 Max: 31336
18.2 µs ± 184 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

 Min: 0
18.3 µs ± 223 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)



 Mean: 15668.0
3.55 ms ± 33.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

 Variance: [81833964.0]
1min 54s ± 1.5 s per loop (mean ± std. dev. of 7 runs, 1 loop each)

 Max: 31336
7.56 ms ± 39.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

 Min: 0
11.8 ms ± 224 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


**Problem 9**

Generate a diagonal matrix with shape (5,5) containing elements in range [1,5] and rotate the matrix by 180 degrees using slicing. The output will be:

[[5, 0, 0, 0, 0],

[0, 4, 0, 0, 0],

[0, 0, 3, 0, 0],

[0, 0, 0, 2, 0],

[0, 0, 0, 0, 1]]

In [32]:
v = np.arange(1,6)
m = np.diag(v)
print(m)
for i in range(len(m)):
    for j in range(len(m)):
        if i == j:
            m[i][j] = len(m)-i

print(m)

#Solution 2
#p = np.diag((5,4,3,2,1))
#print(p)

#Solution 3
#n = np.array([5,4,3,2,1])
#print(np.diag(n))

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
[[5 0 0 0 0]
 [0 4 0 0 0]
 [0 0 3 0 0]
 [0 0 0 2 0]
 [0 0 0 0 1]]


**Problem 10**

Generate 4 matrices of random integers in range \[10,20) with shape(3,3). Use hstack and vstack functions to obtain a 6 by 6 matrix from those 4 matrices. Do the same with np.concatenate function.

In [14]:
mat1 = np.random.randint(10,20,(3,3))
mat2 = np.random.randint(10,20,(3,3))
mat3 = np.random.randint(10,20,(3,3))
mat4 = np.random.randint(10,20,(3,3))
print(f" First Matrix: \n {mat1} \n\n Second Matrix: \n {mat2} \n\n Third Matrix: \n {mat3} \n\n Fourth Matrix: \n {mat4} \n\n")

mat6by3one = np.hstack((mat1,mat2))
mat6by3two = np.hstack((mat3,mat4))
mat6by6 = np.vstack((mat6by3one, mat6by3two))
print(f" Stacked Matrix: \n {mat6by6} \n")


mataxis0one = np.concatenate((mat1,mat2), axis = 0)
mataxis0two = np.concatenate((mat3,mat4), axis = 0)
mat6by6two = np.concatenate((mataxis0one,mataxis0two), axis = 1)
print(f" Second Stacked Matrix: \n {mat6by6two}")

 First Matrix: 
 [[11 19 14]
 [18 12 19]
 [18 14 15]] 

 Second Matrix: 
 [[13 15 18]
 [18 18 16]
 [16 12 11]] 

 Third Matrix: 
 [[19 14 10]
 [19 18 15]
 [10 19 19]] 

 Fourth Matrix: 
 [[11 15 11]
 [11 15 14]
 [10 10 14]] 


 Stacked Matrix: 
 [[11 19 14 13 15 18]
 [18 12 19 18 18 16]
 [18 14 15 16 12 11]
 [19 14 10 11 15 11]
 [19 18 15 11 15 14]
 [10 19 19 10 10 14]] 

 Second Stacked Matrix: 
 [[11 19 14 19 14 10]
 [18 12 19 19 18 15]
 [18 14 15 10 19 19]
 [13 15 18 11 15 11]
 [18 18 16 11 15 14]
 [16 12 11 10 10 14]]


**Problem 11**

Generate a 100x100 dimensional array containing only integer 100 and flatten that array using reshape() function.

In [5]:
arr100x100 = np.tile([100],(100,100))
print(f" 100x100 Ddimensional Array: \n {arr100x100} \n")
flattenedarr = arr100x100.reshape(1,10000)
print(f" Flattened Array: \n {flattenedarr}")

 100x100 Ddimensional Array: 
 [[100 100 100 ... 100 100 100]
 [100 100 100 ... 100 100 100]
 [100 100 100 ... 100 100 100]
 ...
 [100 100 100 ... 100 100 100]
 [100 100 100 ... 100 100 100]
 [100 100 100 ... 100 100 100]] 

 Flattened Array: 
 [[100 100 100 ... 100 100 100]]


**Problem 12**

Generate a numpy array with shape (10,10) and integers in range \[0,100) in column-major order and perform transpose operation on it with numpy built-in method and with slicing (second approach may seem harder). 

In [83]:
arr10 = np.arange(0,100)
arr10x10 = arr10.reshape(10,10,order="F")
print(f" Array with shape(10,10): \n {arr10x10} \n")

trsofarr = arr10x10.transpose()
print(f" Outcome with the first approach: \n {trsofarr} \n")


#a[0][0] -> a[0][0], a[0][1] -> a[1][0],...,a[1][1] -> a[1][1], a[1][0] -> a[0][1],...


newarr10x10 = []
for i in range(len(arr10x10)):
    for j in range(len(arr10x10)):
        if i == j:
            newarr10x10.append(arr10x10[i][j])
        else:
            newarr10x10.append(arr10x10[j][i])
newarr10x10 = np.array(newarr10x10)
print(f" Outcome with another approach: \n {newarr10x10.reshape(10,10)} \n")


secondarr10 = np.arange(0,100) #creating the same array again
secondarr10x10 = secondarr10.reshape(10,10,order="F")

for i in range(len(arr10x10)):
    for j in range(len(arr10x10)):
        if i == j:
            arr10x10[i][j] = arr10x10[i][j] #because the diagonal digits do not change (a[0][0] -> a[0][0]....)
        elif j < i:
            arr10x10[i][j] = secondarr10x10[j][i]  # I am doing this, because without this condition, the elements in the bellow-left corner will be changed twice
        else: 
            arr10x10[i][j] = arr10x10[j][i]

#also, I have created the same array twice, because without secondarr10x10, I will not be able to assighn half of the elements, as I need them unchanged
#without it, my outcome would have been:
#[[ 0 10 20 30 40 50 60 70 80 90]
#[ 1 11 21 31 41 51 61 71 81 91]
#[ 2 12 22 32 42 52 62 72 82 92]
#[ 3 13 23 33 43 53 63 73 83 93]
#[ 4 14 24 34 44 54 64 74 84 94]
#[ 5 15 25 35 45 55 65 75 85 95]
#[ 6 16 26 36 46 56 66 76 86 96]
#[ 7 17 27 37 47 57 67 77 87 97]
#[ 8 18 28 38 48 58 68 78 88 98]
#[ 9 19 29 39 49 59 69 79 89 99]]
#As you can see, the elements of the bellow-left corner, with the following indices are changes twice: [1][0], [2][0], [2][1], [3][0], [3][1], [3][2],...

print(f" Outcome with slicing: \n {arr10x10}")


 Array with shape(10,10): 
 [[ 0 10 20 30 40 50 60 70 80 90]
 [ 1 11 21 31 41 51 61 71 81 91]
 [ 2 12 22 32 42 52 62 72 82 92]
 [ 3 13 23 33 43 53 63 73 83 93]
 [ 4 14 24 34 44 54 64 74 84 94]
 [ 5 15 25 35 45 55 65 75 85 95]
 [ 6 16 26 36 46 56 66 76 86 96]
 [ 7 17 27 37 47 57 67 77 87 97]
 [ 8 18 28 38 48 58 68 78 88 98]
 [ 9 19 29 39 49 59 69 79 89 99]] 

 Outcome with the first approach: 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]] 

 Outcome with another approach: 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 

**Problem 13**

Create a diagonal matrix with integers in range [1,10] on the diagonal. Extract the diagonal elements using slicing.

In [15]:
#creating the given diagonal matrix without np.diag() 
arr1to10 = np.eye((10), dtype=int)
k = 1
for i in range(len(arr1to10)):
    for j in range(len(arr1to10)):
        if arr1to10[i][j] == 1:
            arr1to10[i][j] = k
            k+=1
        else:
            arr1to10[i][j] = arr1to10[i][j]
            
print(f"{arr1to10} \n")

#Or, the same arr1to10 can be simply created with the bellow code
#arr1to10copy = np.diag([1,2,3,4,5,6,7,8,9,10])
#print(arr1to10copy)


#diagonal indices are [0][0],[1][1],...,[9][9]

#Solution 1 (slicing)
diag = np.array([arr1to10[i:i+1,i:i+1] for i in range(10)])
print(f" Solution 1 \n {diag} \n")

#Solution 2
diag2 = [arr1to10[arr1to10 > 0]]
print(f" Solution 2 \n {diag2} \n")

#Solution 3
lst = []
for i in range(len(arr1to10)):
    for j in range(len(arr1to10)):
        if i == j:
            lst.append(arr1to10[i][j])

print(f" Solution 3 \n {lst} \n")

[[ 1  0  0  0  0  0  0  0  0  0]
 [ 0  2  0  0  0  0  0  0  0  0]
 [ 0  0  3  0  0  0  0  0  0  0]
 [ 0  0  0  4  0  0  0  0  0  0]
 [ 0  0  0  0  5  0  0  0  0  0]
 [ 0  0  0  0  0  6  0  0  0  0]
 [ 0  0  0  0  0  0  7  0  0  0]
 [ 0  0  0  0  0  0  0  8  0  0]
 [ 0  0  0  0  0  0  0  0  9  0]
 [ 0  0  0  0  0  0  0  0  0 10]] 

 Solution 1 
 [[[ 1]]

 [[ 2]]

 [[ 3]]

 [[ 4]]

 [[ 5]]

 [[ 6]]

 [[ 7]]

 [[ 8]]

 [[ 9]]

 [[10]]] 

 Solution 2 
 [array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])] 

 Solution 3 
 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] 



**Problem 14**

Create a 4x4 dimensional array where each row corresponds to integers from [1,4] in decreasing order and sort it rowwise. Now repeat the same operation using argsort and slicing.

In [9]:
#Solution 1(With lists)
lstone = list(range(1,5))
lstrone = sorted(lstone,reverse=True)
arr4x4rone = np.tile(lstrone,((4,1)))
print(f"\nSolution 1 \n{arr4x4rone} \n")

#Solution with slicing
arr4x4two = np.tile((range(1,5)),(4,1))
arr4x4rtwo = arr4x4two[0:4,::-1]
print(f"Solution with slicing \n{arr4x4rtwo} \n")

#Solution with argsort
arr4x4three = np.tile((range(1,5)),(4,1))
indicesofsorted = np.argsort(arr4x4three)[::4]
arr4x4rthree = arr4x4three[indicesofsorted,::-1]
print(f" Solution with argsort \n {arr4x4rthree}")


Solution 1 
[[4 3 2 1]
 [4 3 2 1]
 [4 3 2 1]
 [4 3 2 1]] 

Solution with slicing 
[[4 3 2 1]
 [4 3 2 1]
 [4 3 2 1]
 [4 3 2 1]] 

 Solution with argsort 
 [[[4 3 2 1]
  [4 3 2 1]
  [4 3 2 1]
  [4 3 2 1]]]


***Problem 15***
<br> 5 students' test scores are stored in the 2-d array "student_scores". Each row stores the corresponding test's scores. <br>
Calculate the mean of grades of each student (columns) and the median of grades per test (rows)?

In [371]:
student_scores = np.array([[92, 94, 88, 91, 87],
                           [79, 100, 86, 93, 91],
                           [87, 85, 72, 90, 92]])

#print(student_scores[0:,0:1]) col1
#print(student_scores[0:,1:2]) col2
#print(student_scores[0:,2:3]) col3
#print(student_scores[0:,3:2]) col4
#print(student_scores[0:,4:3]) col5


#print(student_scores[0:1,0:]) row1
#print(student_scores[1:2,0:]) row2
#print(student_scores[2:3,0:]) row3

#print(student_scores[0:1,2:3]) median of row1

In [372]:
allstudents = [student_scores[0:,i:i+1] for i in range(len(student_scores[1]))] #seperating each students' grades, so they will be in one array each

listofmeans = [(sum(allstudents[i]) / len(allstudents[i])) for i in range(len(student_scores[1]))]
print(f"  List of the mean of grades of each student \n {listofmeans} \n")



alltests = [np.sort(student_scores[i:i+1,0:]) for i in range(len(student_scores))] #similarly, seperating each row, to have grades for each test in seperate arrays
print(f"  List of grades for each test sorted in increasing order \n {alltests} \n")


#print(alltests[1][0:1,2:3]) median of the first tests grades. I wrote [1] because as I used np.sort(), now I have array inside of array (requires one more iteration)
listofmedians = [alltests[i][0:1,2:3] for i in range(3)]
print(f"  List of medians of each test \n {listofmedians} \n ")

  List of the mean of grades of each student 
 [array([86.]), array([93.]), array([82.]), array([91.33333333]), array([90.])] 

  List of grades for each test sorted in increasing order 
 [array([[87, 88, 91, 92, 94]]), array([[ 79,  86,  91,  93, 100]]), array([[72, 85, 87, 90, 92]])] 

  List of medians of each test 
 [array([[91]]), array([[91]]), array([[87]])] 
 


**Problem 16**<br>
Create a logical statement that selects elements in "porridge" array that are less than 60, and saves them in a new array called "cold".<br>
Create a logical statement that finds all elements that are higher than 80 and saves them in an array named "hot".

In [5]:
porridge = np.array([79, 65, 50, 63, 56, 90, 85, 98, 79, 51])

In [6]:
#Solution 1
cold = np.array([i for i in porridge if i < 60])
print(f" Solution 1 \n cold \n {cold} \n ")

hot = np.array([i for i in porridge if i > 80])
print(f" Solution 1 \n hot \n {hot} \n ")



#Solution 2
cold2 = np.array([],dtype=int)
for i in porridge:
    if i < 60:
        cold2 = np.append(cold2, [i],)
print(f" Solution 2 \n cold \n {cold2} \n ")

hot2 = np.array([],dtype=int)
for i in porridge:
    if i > 80:
        hot2 = np.append(hot2, [i],)
print(f" Solution 2 \n hot \n {hot2} \n ")


 Solution 1 
 cold 
 [50 56 51] 
 
 Solution 1 
 hot 
 [90 85 98] 
 
 Solution 2 
 cold 
 [50 56 51] 
 
 Solution 2 
 hot 
 [90 85 98] 
 


# END